### ISSUE TITLE
[HW13] Веб-серверы (тестирование производительности)

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/dmitry-rakovets#14]
**Дедлайн: 07/09/2023**<br /><br />1. Скопировать папку https://github.com/tms-dos17-onl/_sandbox/tree/main/lecture15/api на VM и запустить Python REST Api приложение согласно инструкции. Проверить работоспособность всех доступных REST Api методов с помощью Swagger.<br />2. Установить Nginx на VM и настроить его как Reverse Proxy для Python REST Api приложения из предыдущего пункта.<br />3. Установить JMeter и написать тестовый сценарий для проверки производительности приложения путем выполнения HTTP GET запроса http://<NGINX_IP>:<NGINX_PORT>/ping от 100 пользователей.<br />4. Запустить ещё один экземпляр Python REST Api приложения на другом порту.<br />5. Изменить конфигурацию Nginx, чтобы он использовал в качестве бэкенда 2 приложения.<br />6. Повторить JMeter сценарий и сравнить результаты.

**Comment by RakovetsD** [comment]
Готово. Просьба принять.
