### ISSUE TITLE
[HW14] Сертификаты TLS

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/dmitry-rakovets#16]
**Дедлайн: 07/09/2023**<br /><br />1. Сгенерировать пару ключей/сертификатов (`private.pem` и `public.pem`) при помощи OpenSSL.<br />2. Создать скрипт `encrypt.sh`, который считывает стандартный поток ввода, шифрует его при помощи `public.pem` через OpenSSL и выводит в стандартный поток вывода.<br />3. Создать скрипт `decrypt.sh`, который считывает стандартный поток ввода, расшифровывает его при помощи `private.pem` через OpenSSL и выводит в стандартный поток вывода.<br />4. Сгенерировать публичный сертификат `public-nginx.pem` для `private.pem` через OpenSSL, используя `<LASTNAME>.io` в качестве Common Name (CN).<br />5. Настроить Nginx на работу по HTTPS, используя сертификаты из предыдущего задания. Например, чтобы Nginx возвращал домашнюю страницу по HTTPS.<br />6. Настроить доверие публичному сертификату в браузере и проверить это.<br />7. А теперь открыть домашнюю страницу Nginx по HTTPS через `curl` не прибегая к опции `-k`.

**Comment by RakovetsD** [comment]
Готово. Просьба принять.
