### ISSUE TITLE
[HW7] Работа с Git

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/dmitry-rakovets#7]
**Дедлайн: 07/08/2023**<br /><br />1. Вывести список всех удаленных репозиториев для локального.<br />2. Вывести список всех веток.<br />3. Вывести последние 3 коммитa с помощью `git log`.<br />4. Создать пустой файл `README.md` и сделать коммит.<br />5. Добавить фразу "Hello, DevOps" в `README.md` файл и сделать коммит.<br />6. Сделать реверт последнего коммита. Вывести последние 3 коммитa с помощью `git log`.<br />7. Удалить последние 3 коммита с помощью `git reset`.<br />8. Вернуть коммит, где добавляется пустой файл `README.md`. Для этого найти ID коммита в `git reflog`, а затем сделать cherry-pick.<br />9. Удалить последний коммит с помощью `git reset`.<br />10. Переключиться на ветку `main` или `master`. Если ветка называется `master`, то переименовать её в `main`.<br />11. Скопировать файл https://github.com/tms-dos17-onl/_sandbox/blob/main/.github/workflows/validate-shell.yaml, положить его по такому же относительному пути в репозиторий. Создать коммит и запушить его в удаленный репозиторий.<br />12. Создать из ветки `main` ветку `develop`. Переключиться на неё и создать `README.md` в корне репозитория. Написать в этом файле какие инструменты DevOps вам знакомы и с какими вы бы хотели познакомиться больше всего (2-3 пункта).<br /><br />> :warning: **Для выполнения задания использовать Markdown, а именно заголовок и списки**<br /><br />13. Создать из ветки `main` ветку `support` и создать там файл `LICENSE` в корне репозитория с содержимым https://www.apache.org/licenses/LICENSE-2.0.txt. Создать коммит. Вывести последние 3 коммитa.<br />14. Переключиться обратно на ветку `main` и создать там файл `LICENSE` в корне репозитория с содержимым https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt. Создать коммит. Вывести последние 3 коммитa.<br />15. Сделать merge ветки `support` в ветку `main` и решить конфликты путем выбора содержимого только одной лицензии.<br />16. Переключиться на ветку `develop` и сделать rebase относительно ветки `main`.<br />17. Вывести историю последних 10 коммитов в виде графа с помощью команды `git log -10 --oneline --graph`.<br />18. Запушить ветку `develop`. В истории коммитов должен быть мерж `support -> main`.<br />19. Зайти в свой репозиторий на GitHub и создать Pull Request из ветки `develop` в ветку `main`.

**Comment by RakovetsD** [comment]
Готово. Просьба проверить.

**Comment by AlexPykavy** [comment]
Всё чётко 😎 Только почему-то не могу замержить Pull Request (PR) из-за мерж конфликта в файлике HW7/hw7.md
![image](https://github.com/tms-dos17-onl/dmitry-rakovets/assets/32162928/a5c52563-eac3-47fc-86d9-d3d25e17011d)

Нужно сделать `git rebase` ветки `develop` относительно последнего состояния `main` и запушить (с опцией `--force` если будет ругаться на расхождение веток).
